[project]
name = "maas-llama-stack"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "llama-stack>=0.2.18",
    "llama-stack-client>=0.2.18",
]
